name: Deploy to production

on:
  push:
    branches:
      - main  # Adjust the branch name if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        # make directory if not exists
        echo "Creating directory on EC2"
        echo ubuntu
        ssh -o StrictHostKeyChecking=no ubuntu@167.99.223.235 'mkdir -p /home/ubuntu/app'
        scp -r -o StrictHostKeyChecking=no ./* ubuntu@167.99.223.235:/home/ubuntu/app
        ssh -o StrictHostKeyChecking=no ubuntu@167.99.223.235 << 'EOF'
          cd /home/ubuntu/app
          nvm use default
          npm i -g yarn pm2
          yarn install
          yarn build
          pm2 restart all
        EOF
