name: Deploy to production

on:
  push:
    branches:
      - main  # Adjust the branch name if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        # make directory if not exists
        echo "Creating directory on EC2"
        echo ${{ secrets.EC2_USER }}
        echo ${{ secrets.EC2_IP_ADDRESS }}
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP_ADDRESS }} 'mkdir -p /home/${{ secrets.EC2_USER }}/app'
        scp -r -o StrictHostKeyChecking=no ./* ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP_ADDRESS }}:/home/${{ secrets.EC2_USER }}/app
        ssh -o StrictHostKeyChecking=no -t ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP_ADDRESS }} << 'EOF'
          cd /home/${{ secrets.EC2_USER }}/app
          source ~/.nvm/nvm.sh
          nvm use default
          npm i -g yarn pm2
          yarn install
          yarn build
          pm2 restart all
        EOF
